### ISSUE TITLE
400 Bad Request 

### ISSUE THREAD

**Issue by DevOpsDCC** [prydin/vrealize-automation-plugin-for-jenkins#6]
I believe there is something wrong with my credential.
What is the full format for the credential and what type should I use?

When accessing the API with Postman I need to specify the refresh token in the body of the POST as well as the API token from the csp gateway.

com.vmware.vra.jenkinsplugin.vra.VRAException: HTTP/1.1 400 Bad Request URL:https://host/iaas/api/login
	at com.vmware.vra.jenkinsplugin.vra.VraClient.executeRequest(VraClient.java:168)
	at com.vmware.vra.jenkinsplugin.vra.VraClient.post(VraClient.java:142)
	at com.vmware.vra.jenkinsplugin.vra.VraClient.post(VraClient.java:116)
	at com.vmware.vra.jenkinsplugin.vra.VraClient.<init>(VraClient.java:70)
	at com.vmware.vra.jenkinsplugin.vra.VraApi.<init>(VraApi.java:77)
	at com.vmware.vra.jenkinsplugin.pipeline.AbstractStep.getClient(AbstractStep.java:53)
	at com.vmware.vra.jenkinsplugin.pipeline.DeployFromCatalogExecution.run(DeployFromCatalogExecution.java:71)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Finished: FAILURE

**Comment by prydin** [comment]
You only need the refresh token. We're also working on a username/password login to be released soon.

**Comment by DevOpsDCC** [comment]
Thanks! I will test it out – If you need some help testing things let me know.
I have vRA 8.2 up in our lab with some other vRealize tools as well

Daniel Clydesdale-Cotter

**Comment by DevOpsDCC** [comment]
The refresh token worked great ! Thanks
